# Generated by Django 4.2.4 on 2023-08-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250, verbose_name='Name')),
                ('url', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='url')),
                ('X', models.CharField(max_length=20, verbose_name='X')),
                ('Y', models.CharField(max_length=20, verbose_name='Y')),
                ('Z', models.CharField(max_length=20, verbose_name='Z')),
                ('Time', models.DateTimeField(max_length=15, verbose_name='Time')),
                ('Cost', models.CharField(max_length=20, verbose_name='Cost')),
                ('Img1', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Img1')),
                ('Img2', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Img2')),
                ('Img3', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Img3')),
                ('Img4', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Img4')),
            ],
            options={
                'verbose_name': 'Вид',
                'verbose_name_plural': 'Види',
            },
        ),
    ]
