# Generated by Django 4.2.4 on 2023-08-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250, verbose_name='Name')),
                ('Phone', models.CharField(max_length=16, verbose_name='Phone')),
                ('url', models.CharField(max_length=50, verbose_name='url')),
                ('Email', models.EmailField(max_length=255, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Вид',
                'verbose_name_plural': 'Види',
            },
        ),
    ]
