# Generated by Django 4.2.4 on 2023-08-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Купця', 'verbose_name_plural': 'Купці'},
        ),
    ]
